# Generated by Django 5.1.3 on 2024-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='no_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
    ]
